version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env.${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - '27017:27017'
    volumes:
      - db_data:/data/db

volumes:
  db_data:
